yaml
services:
  - type: web
    name: telegram-url-uploader-bot
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ID
        value: 20288994
      - key: API_HASH
        value: d702614912f1ad370a0d18786002adbf
      - key: BOT_TOKEN
        value: 8370060694:AAGkcQUUkxne2v5Rh0EhKFGX88Te-kHNG7g
      - key: BOT_USERNAME
        value: "@Urluploader_z_bot"
      - key: DATABASE_URL
        value: mongodb+srv://moviedatabase:venura%408907@cluster0.hg0etvt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: LOG_CHANNEL
        value: -1002897456594
      - key: OWNER_ID
        value: 8312532076
      - key: SESSION_STR
        value: ""
      - key: UPDATE_CHANNEL
        value: https://t.me/zerodevbro
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true
